[[snippets]]
  description = "Convert seconds since the epoch (1970-01-01 UTC) to a date"
  command = "date -d @1440359821"
  tag = ["epoch"]
  output = "Sun Aug 23 15:57:01 EDT 2015"

[[snippets]]
  description = "Date / timestamp as seconds since epoch"
  command = "date -d `date +%FT%TZ` +%s"
  tag = ["timestamp", "epoch"]
  output = "1551295966"

[[snippets]]
  description = "Recursively grep for string <pattern> in folder and print matching files"
  command = "grep -Rl pattern folder"
  tag = ["recurse"]
  output = ""

[[snippets]]
  description = "Find lines NOT containing pattern"
  command = "grep -v pattern file"
  tag = ["not"]
  output = ""

[[snippets]]
  description = "Date / timestamp human readable"
  command = "date +\"%Y%m%d_%H%M%S\""
  tag = ["timestamp"]
  output = "20190228_120344"

[[snippets]]
  description = "Encrypt string with OpenSSL"
  command = "echo string | openssl aes-256-cbc -pbkdf2 -e | openssl base64 -e"
  tag = ["encryption", "openssl", "aes-256"]
  output = "U2FsdGVkX193oGHZmNNRtU/3oczNZNJpUUGad3vhKtg="

[[snippets]]
  description = "Decrypt string with OpenSSL"
  command = "echo \"U2FsdGVkX193oGHZmNNRtU/3oczNZNJpUUGad3vhKtg=\" | openssl base64 -d | openssl aes-256-cbc -pbkdf2 -d"
  tag = ["encryption", "openssl", "aes-256"]
  output = "string"

[[snippets]]
  description = "Encrypt file with OpenSSL"
  command = "openssl aes-256-cbc -pbkdf2 -e -in DECFILE -out ENCFILE"
  tag = ["encryption", "openssl", "aes-256"]
  output = ""

[[snippets]]
  description = "Decrypt file with OpenSSL"
  command = "openssl aes-256-cbc -pbkdf2 -d -in ENCFILE -out DECFILE"
  tag = ["encryption", "openssl", "aes-256"]
  output = ""

[[snippets]]
  description = "Encrypt directory with OpenSSL"
  command = "tar cz DIR | openssl aes-256-cbc -pbkdf2 -e -out ENCFILE"
  tag = ["encryption", "openssl", "aes-256"]
  output = ""

[[snippets]]
  description = "Decrypt directory with OpenSSL"
  command = "openssl aes-256-cbc -pbkdf2 -d -in ENCFILE | tar xz"
  tag = ["encryption", "openssl", "aes-256"]
  output = ""

[[snippets]]
  description = "Write ISO image to USB drive"
  command = "dd if=FILE.iso of=/dev/sdX bs=4M status=progress && sync"
  tag = ["iso", "usb", "livecd"]
  output = ""

[[snippets]]
  description = "dconf write string"
  command = "dconf write /com/deepin/wrap/gnome/desktop/wm/preferences/focus-mode \"string 'sloppy'\""
  tag = ["dconf", "string"]
  output = ""

[[snippets]]
  description = "dconf write boolean or integer"
  command = "dconf write /com/deepin/wrap/gnome/desktop/wm/preferences/auto-raise false"
  tag = ["dconf", "boolean", "integer"]
  output = ""

[[snippets]]
  description = "Screenshot website"
  command = "/bin/google-chrome-unstable --headless --hide-scrollbars --screenshot=\"$HOME/Downloads/FILE\" \"URL\" # --window-size=1024,2550"
  tag = ["chrome", "screenshot", "website"]
  output = ""

[[snippets]]
  description = "Display A/V File Tags"
  command = "ffprobe FILE"
  tag = ["ffmpeg", "ffprobe", "tags", "audio", "video"]
  output = ""

[[snippets]]
  description = "Create & checkout new branch"
  command = "git checkout -b <BRANCH>"
  tag = ["git", "branch"]
  output = ""

[[snippets]]
  description = "Delete local branch"
  command = "git branch -d <LOCAL_BRANCH>"
  tag = ["git", "branch"]
  output = ""

[[snippets]]
  description = "Delete remote branch"
  command = "git push origin --delete <REMOTE_BRANCH>"
  tag = ["git", "branch"]
  output = ""

[[snippets]]
  description = "Copy files from another branch into current"
  command = "git checkout <BRANCH> <PATHS>..."
  tag = ["git", "branch", "copy", "files"]
  output = ""

[[snippets]]
  description = "Optimize png images and strip all metadata"
  command = "optipng -strip all image.png"
  tag = ["images", "png", "optimize"]
  output = ""

[[snippets]]
  description = "Resize images while preserving aspect ratio (200x100! will force size)"
  command = "convert example.png -resize 200x100 example.png"
  tag = ["imagemagick", "images", "resize"]
  output = ""

[[snippets]]
  description = "parse XML file (stdin = -) for tag value (beware XMLNS)"
  command = "echo \"<dewpoint_f>26.1</dewpoint_f>\" |  xmllint --xpath \"string(//dewpoint_f)\" -"
  tag = ["xml", "parse"]
  output = "26.1"

[[snippets]]
  description = "ImageMagick convert BG to transparent (PNG or GIF support transparency)"
  command = "convert IMAGE.{gif|png} -transparent white IMAGE.{gif|png}"
  tag = ["imagemagick", "transparent", "background"]
  output = ""

[[snippets]]
  description = "Add user to multiple groups"
  command = "sudo usermod -aG GROUP1,GROUP2 USER"
  tag = ["users", "groups"]
  output = ""

[[snippets]]
  description = "Remove package depended upon by another package"
  command = "pacman -Rdd wpa_supplicant"
  tag = ["pacman", "remove", "dependencies"]
  output = ""

[[snippets]]
  description = "Restart Plasma"
  command = "plasmashell --replace &"
  tag = ["plasma", "restart"]
  output = ""

[[snippets]]
  description = "Show tree view of mounted filesystems"
  command = "findmnt"
  tag = ["mount", "filesystems"]
  output = ""

[[snippets]]
  description = "Play podcast @ 1.5x speed without affecting pitch optimized for speech"
  command = "play science-friday121418a.mp3 tempo -s 1.5"
  tag = ["audio", "podcasts", "sox"]
  output = ""

[[snippets]]
  description = "Convert podcast to 1.5x speed without affecting pitch optimized for speech & show progress"
  command = "sox -S science-friday121418a.mp3 test.mp3 tempo -s 1.5"
  tag = ["audio", "podcast", "sox", "convert"]
  output = ""

[[snippets]]
  description = "Play podcast @ 1.5x speed without affecting pitch"
  command = "mplayer -af scaletempo -speed 1.5 HSW9914000083.mp3"
  tag = ["audio", "podcasts", "mplayer"]
  output = ""

[[snippets]]
  description = "Rename files to UTF8, special chars to _, & lowercase"
  command = "detox -s utf_8 -s lower *"
  tag = ["rename", "detox", "filenames", "files"]
  output = ""

[[snippets]]
  description = "List apps not in a registered repo or PPA"
  command = "apt-show-versions | grep 'No available version'"
  tag = ["apt", "packages", "repos"]
  output = ""

[[snippets]]
  description = "List packages from a particular repo or PPA"
  command = "awk '$1 == \"Package:\" { if (a[$2]++ == 0) print $2; }' /var/lib/apt/lists/*PARTOFREPONAME*Packages"
  tag = ["apt", "packages", "repos"]
  output = ""

[[snippets]]
  description = "Grep exclude by regex"
  command = "grep -Ev \"^(PAT1|PAT2|PAT3)\""
  tag = ["grep", "exclude", "not", "regex", "pattern"]
  output = ""

[[snippets]]
  description = "Concatenate video files (same type) w/ffmpeg"
  command = "ffmpeg -i \"concat:VTS_02_1.VOB|VTS_02_2.VOB|VTS_02_3.VOB\" -c copy COMBINED.vob"
  tag = ["ffmpeg", "cat", "combine", "video"]
  output = ""

[[snippets]]
  description = "Concatenate MKV video files"
  command = "mkvmerge -o COMBINED.mkv 1-1.mkv +1-2.mkv +1-3.mkv +..."
  tag = ["video", "concatenate", "mkv", "mkvmerge"]
  output = ""

[[snippets]]
  description = "Backup DVD main feature to hd"
  command = "dvdbackup -i /dev/sr0 -o ~/Videos/ -F -p"
  tag = ["dvd", "backup", "dvdbackup", "video"]
  output = ""
