# espanso match file
# https://espanso.org/docs/

matches:
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from $SHELL"
